apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: ecommerce
type: Opaque
data:
  # mongodb://admin:mongodb_password@mongodb:27017/products_db
  username: YWRtaW4=  # admin
  password: bW9uZ29kYl9wYXNzd29yZA==  # mongodb_password
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ecommerce
type: Opaque
data:
  # postgres://postgres:postgres_password@postgres:5432/users_db
  username: cG9zdGdyZXM=  # postgres
  password: cG9zdGdyZXNfcGFzc3dvcmQ=  # postgres_password
  database: dXNlcnNfZGI=  # users_db
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: ecommerce
type: Opaque
data:
  password: cmVkaXNfcGFzc3dvcmQ=  # redis_password
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: ecommerce
type: Opaque
data:
  username: ZWxhc3RpYw==  # elastic
  password: ZWxhc3RpY19wYXNzd29yZA==  # elastic_password
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: ecommerce
type: Opaque
data:
  secret-key: eW91ci1zZWNyZXQta2V5LWhlcmU=  # your-secret-key-here