version: '3.8'

# Docker Compose file for building and testing base images locally

services:
  # Local Docker Registry for base images
  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - registry_data:/var/lib/registry
    restart: unless-stopped

  # Base image build service
  base-builder:
    build:
      context: .
      dockerfile: node-base.Dockerfile
    image: localhost:5000/ecommerce-node-base:latest
    container_name: base-builder
    depends_on:
      - registry
    profiles:
      - build

  # Test services for base images
  test-node:
    image: localhost:5000/ecommerce-node-base:latest
    container_name: test-node-base
    command: node --version
    profiles:
      - test

  test-java:
    image: localhost:5000/ecommerce-java-base:latest
    container_name: test-java-base
    command: java --version
    profiles:
      - test

  test-python:
    image: localhost:5000/ecommerce-python-base:latest
    container_name: test-python-base
    command: python --version
    profiles:
      - test

  # Image scanning service
  security-scanner:
    image: localhost:5000/ecommerce-security-scanner:latest
    container_name: security-scanner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scan-results:/workspace/results
    command: >
      sh -c "
        echo 'Scanning base images for vulnerabilities...'
        trivy image localhost:5000/ecommerce-node-base:latest --format json --output /workspace/results/node-base-scan.json
        trivy image localhost:5000/ecommerce-java-base:latest --format json --output /workspace/results/java-base-scan.json
        trivy image localhost:5000/ecommerce-python-base:latest --format json --output /workspace/results/python-base-scan.json
        echo 'Security scans completed. Check results in ./scan-results/'
      "
    profiles:
      - security

volumes:
  registry_data:

networks:
  default:
    name: base-images-network