_format_version: "3.0"
_transform: true

# Service definitions
services:
  # Product Catalog Service
  - name: product-catalog-service
    url: http://product-catalog:3001
    retries: 5
    connect_timeout: 30000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - microservice
      - phase2
    
    routes:
      - name: product-catalog-routes
        paths:
          - /api/products
        strip_path: false
        preserve_host: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        tags:
          - products

  # User Profile Service
  - name: user-profile-service
    url: http://user-profile:3002
    retries: 5
    connect_timeout: 30000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - microservice
      - phase2
    
    routes:
      - name: user-profile-routes
        paths:
          - /api/users
          - /api/auth
        strip_path: false
        preserve_host: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        tags:
          - users
          - auth

  # Shopping Cart Service
  - name: shopping-cart-service
    url: http://shopping-cart:3003
    retries: 5
    connect_timeout: 30000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - microservice
      - phase2
    
    routes:
      - name: shopping-cart-routes
        paths:
          - /api/cart
        strip_path: false
        preserve_host: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        tags:
          - cart

  # Search Service
  - name: search-service
    url: http://search:3004
    retries: 5
    connect_timeout: 30000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - microservice
      - phase2
    
    routes:
      - name: search-routes
        paths:
          - /api/search
        strip_path: false
        preserve_host: true
        methods:
          - GET
          - POST
        tags:
          - search

  # Frontend Service
  - name: frontend-service
    url: http://react-store-ui:3000
    retries: 3
    connect_timeout: 30000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - frontend
      - phase3
    
    routes:
      - name: frontend-routes
        paths:
          - /
        strip_path: false
        preserve_host: true
        methods:
          - GET
        tags:
          - frontend

# Global plugins
plugins:
  # CORS Configuration
  - name: cors
    config:
      origins:
        - http://localhost:3000
        - http://localhost:8000
        - https://yourdomain.com
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600
      preflight_continue: false

  # Rate Limiting
  - name: rate-limiting
    config:
      minute: 100
      hour: 10000
      policy: local
      fault_tolerant: true
      hide_client_headers: false
      redis_ssl: false
      redis_ssl_verify: false

  # Request Size Limiting
  - name: request-size-limiting
    config:
      allowed_payload_size: 10
      size_unit: megabytes

  # Prometheus Metrics
  - name: prometheus
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true

# Consumer definitions (for future authentication)
consumers:
  - username: frontend-app
    tags:
      - frontend
    
  - username: mobile-app
    tags:
      - mobile
    
  - username: admin-user
    tags:
      - admin

# Upstream definitions for load balancing
upstreams:
  - name: product-catalog-upstream
    algorithm: round-robin
    slots: 10000
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 5
          successes: 2
        unhealthy:
          interval: 5
          http_failures: 5
          tcp_failures: 5
          timeouts: 5
    targets:
      - target: product-catalog:3001
        weight: 100

  - name: user-profile-upstream
    algorithm: round-robin
    slots: 10000
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 5
          successes: 2
        unhealthy:
          interval: 5
          http_failures: 5
          tcp_failures: 5
          timeouts: 5
    targets:
      - target: user-profile:3002
        weight: 100

  - name: shopping-cart-upstream
    algorithm: round-robin
    slots: 10000
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 5
          successes: 2
        unhealthy:
          interval: 5
          http_failures: 5
          tcp_failures: 5
          timeouts: 5
    targets:
      - target: shopping-cart:3003
        weight: 100

  - name: search-upstream
    algorithm: round-robin
    slots: 10000
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 5
          successes: 2
        unhealthy:
          interval: 5
          http_failures: 5
          tcp_failures: 5
          timeouts: 5
    targets:
      - target: search:3004
        weight: 100